add images and Software Engineering Career Track as only course
4GeeksAcademy/bocacode-website pull request #1
Opened 2024-02-25 03:25 UTC by Khrisefzm

Issue Link: https://github.com/orgs/breatheco-de/projects/8/views/1?filterQuery=assignee%3AKhrisefzm&pane=issue&itemId=46950653

Solo dejé como curso: Software Engineering Career Track, pues no existía en el JSON Full Stack Developer como tal.

2024-02-27 18:46 UTC, tommygonzaleza commented
Fallo el deployment, este es el error que muestra en el log:
![Screenshot 2024-02-27 at 2 45 48 PM](https://github.com/4GeeksAcademy/bocacode-website/assets/56565994/ce587084-2d48-41c5-b001-bea73cc73c0e)

2024-03-19 20:25 UTC, tommygonzaleza requested changes

2024-03-19 20:25 UTC, tommygonzaleza commented on app/components/Card/page.js
> +          profile
Es mejor tener estas condiciones antes donde esta el resto del codigo js, y lo guardas en una variables para luego usarlo aqui

2024-03-19 20:25 UTC, tommygonzaleza commented on app/components/Navbar/page.js
> +                height={0}
Ponle el height del logo cuando el width es 124px y quita el height auto

2024-03-19 20:25 UTC, tommygonzaleza commented on app/components/PageHeader/page.js
> +  // const { heading, sub_heading, content, button_1, button_2 } = data;
Descomenta y utiliza con el nombre de las variables nuevas

2024-03-19 20:25 UTC, tommygonzaleza commented on app/components/UpcomingDates/page.js
>  const UpcomingDates = ({ data }) => {
Puedes hacer lo mismo que se recomendo en la otra pagina, obten los valores del objeto data y declaralos al inicio para poder utilizarlos luego sin tener que acceder a traves de data

2024-03-20 18:04 UTC, Khrisefzm commented on app/components/PageHeader/page.js
> +  // const { heading, sub_heading, content, button_1, button_2 } = data;
No es posible hacerlo porque por algún motivo el deployment falla al usarlo

2024-04-10 14:48 UTC, merged